- name: Disable redis and enable redis version 7
  ansible.builtin.shell: dnf module disable redis -y ; dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update redis conf file listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update redis config file protected mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Enable and start redis
  ansible.builtin.systemd:
    name: redis
    daemon_reload: yes
    state: restarted
    enabled: yes


