- name: Load Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: docker.yaml

- name: Run frontend docker
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: restarted
    recreate: true
    exposed_ports:
      - 6379
    volumes_from:
      - mydata
