- name: Load Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: docker.yaml




- name: Load frontend secrets from Vault
  ansible.builtin.set_fact:
    vault_secrets: "{{ lookup('community.hashi_vault.hashi_vault',
      'secret=roboshop-dev-docker-secrets/data/frontend-docker token={{ vault_token }} url=http://vault.devopsbymanju.shop:8200') }}"
                     'secret=roboshop-' ~ env ~ '-secrets/data/' ~ component ~ ' token={{ vault_token }} url=http://vault.devopsbymanju.shop:8200') }}"
    component: "{{ component_name | regex_replace('-docker', '') }}"
  vars:
    component: "{{ component_name | regex_replace('-docker', '') }}"

- name: Run frontend docker
- name: Run  docker container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ component }}
    state: started
    recreate: true
    ports:
      - "80:80"
      - "{{ app_port }}:{{ app_port }}"
    env: "{{ secrets }}"

- name: Load secrets from Vault
  ansible.builtin.set_fact:
    component: "{{ component_name | regex_replace('-docker', '') }}"
    vault_secrets: >-
      {{ lookup(
        'community.hashi_vault.hashi_vault',
        'secret=roboshop-' ~ env ~ '-secrets/data/' ~
        (component_name | regex_replace("-docker", "")) ~
        ' token=' ~ vault_token ~
        ' url=http://vault.devopsbymanju.shop:8200'
      ).data.data }}