- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven.yaml

- name: Install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.devopsbymanju.shop -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load user creation
  ansible.builtin.shell: mysql -h mysql-dev.devopsbymanju.shop -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load master data
  ansible.builtin.shell: mysql -h mysql-dev.devopsbymanju.shop -uroot -pRoboShop@1 < /app/db/master-data.sql