- name: Load Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yaml

#- name: Copy service file form user files
#  ansible.builtin.copy:
#    src: user.service
#    dest: /etc/systemd/system/user.service

#- name: Install mongod
#  ansible.builtin.dnf:
#    name: mongodb-mongosh
#    state: installed
#
#- name: Load Master data schema
#  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.devopsbymanju.shop </app/db/master-data.js
