#  func_python(){
#
#    func_print_head "Install Python"
#    dnf install python3 gcc python3-devel -y &>>${log_file}
#    func_status_check $?
#
#    func_app_prereq
#
#    func_print_head "Download python dependencies" &>>${log_file}
#    pip3 install -r requirements.txt  &>>${log_file}
#    func_status_check $?
#
#    func_print_head "Update RabbitMQ credentials in SystemD service file"
#    sed -i -e "s|^Environment=AMQP_USER=.*|Environment=AMQP_USER=${rabbitmq_app_username}|" \
#    -e "s|^Environment=AMQP_PASS=.*|Environment=AMQP_PASS=${rabbitmq_app_users_password}|" \
#    "${script_path}/${component}.service" &>>${log_file}
#    #     sed -i -e "s|rabbitmq_app_username|${rabbitmq_app_username}|g" ${script_path}/${component}.service &>>${log_file}
#    #     sed -i -e "s|rabbitmq_app_users_password|${rabbitmq_app_users_password}|g" ${script_path}/${component}.service &>>${log_file}
#    func_status_check $?
#
#    func_systemd_setup
#
#  }

- name: Load python
  ansible.builtin.include_role:
    name: common
    tasks_from: python.yaml

