- name: Copy repo file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Enable and start rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add user and password
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"



