- name: Load Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: docker.yaml
  vars:
    app_port: 8080

- name: Run docker to load schema
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: present
    recreate: true
    env: "{{ schema_secrets }}"


