- name: Disable Nodejs and enable nodejs version 20
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs version 20
  ansible.builtin.shell: dnf module enable nodejs:20

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed
    enabled: yes

- name: Include app_prereq task list in play
  ansible.builtin.include_tasks:
    file: app_prereq.yaml

- name: Install Nodejs dependencies
  ansible.builtin.shell: npm install

- name: Include schema setup tasks list in play
  ansible.builtin.include_tasks:
    file: schema_setup.yaml

- name: Include systemd setup tasks list in play
  ansible.builtin.include_tasks:
    file: systemd_setup.yaml


