#if [ "$schema_setup" == "mongo" ]; then
#func_print_head "Copy mongod repo from mongo.repo"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#func_status_check $?
#
#func_print_head "Install mongodb"
#dnf install mongodb-mongosh -y &>>${log_file}
#func_status_check $?
#
#func_print_head "Connect to schema"
#mongosh --host mongodb-dev.devopsbymanju.shop </app/db/master-data.js &>>${log_file}
#func_status_check $?
#fi

- name: Copy mongod repo from catalogue files
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongod
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Connect to schema
  ansible.builtin.shell: mongosh --host {{ component_name }}-dev.devopsbymanju.shop
